### ISSUE TITLE
"No existing Cytoscape window named ..."

### ISSUE THREAD

**Issue by pshannon-bioc** [tmuetze/Bioconductor_RCy3_the_new_RCytoscape#3]
Very minor.   Whenever I issue

  cw <- CytoscapeWindow("gbm mutations", g.mut, overwriteWindow=(TRUE or FALSE)

I always see:

  No existing Cytoscape window named 'gbm mutations'

even though (hurray!) everything works fine.

**Comment by tmuetze** [comment]
This is because the CytoscapeWindow function calls the getWindowID function which prints that sentence. We added that sentence in the getWindowID function to inform the user - who is querying a certain window name - whether or not it exists.
Solution:
The getWindowID function now prints: "Cytoscape window named 'test' does not exist yet" and the CytoscapeWindow function adds: "New window named "test" was created in Cytoscape." with test replaced by the current window name.
